# .github/workflows/dbt.yml
name: dbt-CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}   # points dbt to the profiles.yml in the repo
  DBT_GOOGLE_KEYFILE: ${{ runner.temp }}/sa.json

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Write the secret to disk so dbt can read it
      - name: Write service-account key
        run: |
          echo '${{ secrets.DBT_BQ }}' > "$DBT_GOOGLE_KEYFILE"

      # 2️⃣  Set up Python and dbt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery==1.7.5
          dbt --version

      # 3️⃣  Run whatever dbt command you need
      - name: Build the warehouse
        run: dbt build --threads 4
