# .github/workflows/dbt.yml
name: dbt-CI

on:
  push:
    branches: [main]
env:
  DBT_PROFILES_DIR: ${{ github.workspace }}  
  
jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1️⃣  Write the secret to disk so dbt can read it
      - name: Write service-account key
        run: |
          echo '${{ secrets.DBT_BQ }}' > "opoor.json"

      # 2️⃣  Set up Python and dbt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery==1.7.5
          dbt --version

      # 3️⃣  Run whatever dbt command you need
      - name: Build the warehouse
        run: dbt build --profiles-dir . --threads 4
