# .github/workflows/dbt.yml
name: dbt-CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:


jobs:
  dbt-build:
    runs-on: ubuntu-latest
    env:
      GCP_DBT_DATASET: ${{ vars.GCP_DBT_DATASET }}
      GCP_BQ_PROJECT: ${{ vars.GCP_BQ_PROJECT }}
      GCP_DBT_KEYFILE: ${{ secrets.DBT_BQ }}
      
    steps:
      - uses: actions/checkout@v4
      # 2️⃣  Set up Python and dbt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery==1.7.5
          dbt --version

      # 3️⃣  Run whatever dbt command you need
      - name: Build the warehouse
        run: dbt build --threads 4
